# environment variables for any dev environment
version: '3'

services:
  # service name has to be environment-unique, else one startup will shutdown others
  local-hystrix-server:
    labels:
      lsb2.template.description: "Hystrix Server for local environment"
      lsb2.version: "local"
    image: "hystrix-server:local"
    build:
      context: ../..
      dockerfile: ./docker/Dockerfile
    ports:
      - "7979:7979" # web port
    environment:
      PROFILE: "local"
      OTTO_GROUP: "local"
    networks:
      - learn-ms-network

networks:
  learn-ms-network:
    external: true


