# environment variables for any dev environment
version: '3'

services:
  # service name has to be environment-unique, else one startup will shutdown others
  local-hystrix-server:
    labels:
      lsb2.template.description: "Hystrix Server for local environment"
      lsb2.version: "local"
    image: "jghamburg/lsb2-hystrix-dashboard:local"
    build:
      context: ../..
      dockerfile: ./docker/Dockerfile
      args:
        JAR_FILE: ./build/libs/lsb2-hystrix-dashboard.jar
    ports:
      - "7979:8080" # web port
    environment:
      PROFILE: "default"
      PORT: 8080
    networks:
      - learn-ms-network

networks:
  learn-ms-network:
    external: true


